# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vegånia
email: info@vegania.fi
excerpt: > # "description:"
  Uusi vegaaniruokatapahtuma Turkuun kesällä – Vegåniassa ei tarjota mitään eläinperäistä
description: > # this means to ignore newlines until baseurl:"
  Elokuussa 2017 järjestetään ensimmäistä kertaa Turussa Vanhalla Suurtorilla Vegånia –
  vegaaniruokafestivaali. 4.–5.8. järjestettävässä tapahtumassa on pääosassa hyvä ruoka, joka on
  kestävästi tuotettua ja eläinten oikeuksia kunnioittavaa. Vegånia ei kuitenkaan ole tapahtuma vain
  vegaaneille, vaan kaikkien kaupunkilaisten yhteinen ruokajuhla.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vegania.github.io" # the base hostname & protocol for your site
twitter:
  username: veganiaturku
facebook:
  app_id: 1
  publisher: 1
  admins: 1
github_username: vegania
gogle_analytics: UA-93333101-1

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - bootstrap
  - autoprefixer-rails

exclude:
  - node_modules
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
