# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vegånia
email: info@vegania.fi
excerpt: > # "description:"
  Tähän sivuston kuvaus, alle 160 merkkiä. Google poimii hakutulossivuille
  automaattisesti.
description: > # this means to ignore newlines until "baseurl:"
  Tähän sivuston kuvaus muutamalla lauseella. Samoin tämä sisällytetään myös feed.xml tiedostoon "site description" kenttään.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vegania.hithub.io" # the base hostname & protocol for your site
twitter_username: veganiaturku
github_username:  vegania

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
