# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Vegånia"
email: info.vegania@gmail.com
excerpt: > # "description:"
  Uusi koko kansan vegaaniruokatapahtuma Turkuun kesällä – Vegåniassa tarjotaan maittavaa ruokaa ympäristöä kunnioittaen
description: > # "baseurl:"
  Vegånia – vegaaniruokafestivaalin pääosassa on maukas ja laadukas ruoka, joka on kestävästi tuotettua ja eettistä.
  Vegånia on tapahtuma vegaaneille ja yhtälailla kaikkien kaupunkilaisten yhteinen ruokajuhla.
  Tapahtuma järjestettiin ensimmäistä kertaa Turun Vanhalla Suurtorilla 4.–5.8.2017.
  Vegånia saa jatkoa vuonna 2018.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vegania.fi" # the base hostname & protocol for your site
twitter:
  username: VeganiaTurku
facebook:
  publisher: https://www.facebook.com/veganiaturku
  admins: 650159652
  username: veganiaturku
github:
  username: vegania
instagram:
  username: info.vegania
google_analytics: UA-93333101-1
logo: /images/share_logo.png
lang: fi_FI

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - bootstrap
  - autoprefixer-rails
  - jekyll-last-modified-at
  - jekyll-sitemap

exclude:
  - node_modules
  - material
  - vendor
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
