# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vegånia
email: info.vegania@gmail.com
excerpt: > # "description:"
  Uusi koko kansan vegaaniruokatapahtuma Turkuun kesällä – Vegåniassa tarjotaan maittavaa ruokaa ympäristöä kunnioittaen
description: > # "baseurl:"
  Elokuussa 2017 Turussa järjestetään ensimmäistä kertaa Vegånia –
  vegaaniruokafestivaali. Vanhan Suurtorin 4.–5.8. täyttävän tapahtuman
  pääosassa on maukas ruoka, joka on laadukasta, kestävästi tuotettua ja
  eettistä. Vegånia on tapahtuma vegaaneille ja yhtälailla kaikkien
  kaupunkilaisten yhteinen ruokajuhla.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vegania.fi" # the base hostname & protocol for your site
twitter:
  username: veganiaturku
facebook:
  app_id: 1
  publisher: 1
  admins: 1
github_username: vegania
gogle_analytics: UA-93333101-1

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - bootstrap
  - autoprefixer-rails

exclude:
  - node_modules
  - material
  - vendor
  - README.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
